var ger1 = [
  "Abgelenkt sein",
  "Angegestrebten berufslaufbahn",
  "Anwendung des Verballists",
  "Auf Biegen und Brechen versuchen",
  "Auf ehrlichkeit beruhren",
  "Aufschlussreich",
  "Ausführliche Darlegung seiner Motivation",
  "Auszeit",
  "Auswahl eines sympathischen Fotos",
  "Beurteilung",
  "Bewusst absolvierte",
  "Der arbeitsablauf",
  "Der erlesenem Genuss",
  "Der Gleichzeitigkeitswahn",
  "Der Richtungswechsel",
  "Der stellenwert",
  "Der studiengang",
  "Die Aufsteigchance",
  "Die auszeit",
  "Die Doppelbelastung",
  "Die fine kürfstliche lebensart",
  "Die Laufbahn",
  "Die Mobilität",
  "Die Promotion",
  "Die probanden",
  "Die stoßstange",
  "Die Zulassungs voraussetzung",
  "Ein abgebrochener Studiengang",
  "Ein bunter Lebenslauf",
  "Ein nur massig",
  "Einheillig wiedersprechen",
  "Ebenso zentral wie selbstverstandlich",
  "Enthält",
  "Erfreuen sich",
  "Fehler ausbügeln",
  "Freude schenken",
  "Fromt sich",
  "Genaue Beschreibung des berüflichen Werdegangs",
  "Grossen Beliebtheit",
  "Handlungsanweisungen",
  "Herstellung",
  "Im Hinblick",
  "Im zweifel gilt daher",
  "Innovationsschub",
  "Klarkommen",
  "Plausibel",
  "Reviedieren",
  "Ruchtungswechsel",
  "Schlüssig",
  "Stark steigender Nachfrage",
  "Stolpersteine",
  "Umgehen",
  "Vielfach prämierten Speisen",
  "Vollzogen",
  "Wahrnehmung",
  "Zeit verplempern",
  "Zielstrebig",
];

var eng1 = [
  "To be distracted",
  "Desired career path",
  "Application of the verbal list",
  "Try by hook or by crook",
  "Based on honesty",
  "Insightful, informative",
  "Detailed explanation of his motivation",
  "Timeout",
  "Selecting a sympathetic photo",
  "Assessment",
  "Consciously completed",
  "The work process",
  "The exquisite pleasure",
  "Simultaneity delusion",
  "Change of direction",
  "The importance",
  "The course of study",
  "The chance of promotion",
  "The timeout",
  "The double burden",
  "The fine princely way of life",
  "The career",
  "The mobility",
  "The promotion",
  "The test subjects",
  "The bumper",
  "The admission requirement",
  "A discontinued course of study",
  "A colorful resume",
  "Only moderately",
  "Unanimously contradict",
  "Just as central as self-evident",
  "Contains",
  "Enjoy",
  "Iron out errors",
  "Give joy",
  "Forms itself",
  "Detailed description of the professional career",
  "Great popularity",
  "Instructions",
  "Manufacturing",
  "In view",
  "Therefore, when in doubt",
  "Innovation boost",
  "Get along",
  "Plausible",
  "Reverse",
  "Direction change",
  "Conclusion",
  "Strongly increasing demand",
  "Stumbling blocks",
  "Avoid",
  "Multiple award-winning dishes",
  "Executed",
  "Perception",
  "Waste time",
  "Determined",
];
var ger2 = [
  "Abgelegenen",
  "Akribisch",
  "Analytisches und logisches Denken",
  "Arbeitsverhältnis",
  "Arbeitsverträge aufsetzen",
  "Auflichten",
  "Ausführlich",
  "Ballungsraum",
  "Beihalten",
  "Belastbarkeit",
  "Berühren",
  "Bescheid",
  "Bestellung versenden",
  "Betriebsräte",
  "Beweis",
  "Darbitten",
  "Der Reihe nach",
  "Der Wandel",
  "Die Kapazität",
  "Die Konsument",
  "Die Priorität",
  "Die Ressource",
  "Die Schlüsselqualifikation",
  "Durchsetzungsvermögen",
  "Einfühlungsvermögen",
  "Einer Illusion erliegen",
  "Etwas nicht gewachsen sein",
  "Fehler ausüben",
  "Floskelhaft",
  "Fortan",
  "Führungskompetenz",
  "Gehaltsabrechnungen erstellen",
  "Gehaltsvorstellungen",
  "Gelangen zu",
  "Grundvoraussetzung",
  "Haufenweise",
  "Herausfiltern",
  "Klarkommen mit",
  "Kommilitonen",
  "Kommunikationsfähigkeit",
  "Konfliktfähigkeit",
  "Kundenorientierung",
  "Lehrreich",
  "Mitarbeiter abmahnen",
  "Neugierig zu stimmen",
  "Pakete frankieren",
  "Passgenau aufzuzeigen",
  "Plausibel",
  "Preise aushandeln",
  "Rabatte gewähren",
  "Rechnungen schreiben",
  "Reklamationen bearbeiten",
  "Scheitern an",
  "Sich auf dem Laufenden halten",
  "Sich einen Überblick verschaffen über",
  "Sich verzögern",
  "Stichwortartig aufzählen",
  "Teamfähigkeit",
  "Umgehen mit",
  "Verhandlungen führen mit",
  "Vermeiden",
  "Verschwenden",
  "Versetzen",
  "Vertrag",
  "Verwechseln",
  "Vieles auf einmal tun",
  "Voraussetzen",
  "Waren annehmen",
  "Waren zusammenstellen",
  "Warenbestände prüfen",
  "Zeit verplempern",
  "Zielstrebig",
  "Zuständig sein für",
];

var eng2 = [
  "Remote",
  "Meticulous",
  "Analytical and logical thinking",
  "Employment relationship",
  "Set up employment contracts",
  "Light up",
  "Detailed",
  "Conurbation",
  "Hold on",
  "Resilience",
  "Touch",
  "Notice",
  "Send order",
  "Works councils",
  "Proof",
  "Offer",
  "In order",
  "The change",
  "The capacity",
  "The consumer",
  "The priority",
  "The resource",
  "The key qualification",
  "Assertiveness",
  "Empathy",
  "To succumb to an illusion",
  "Not being up to something",
  "Make a mistake",
  "Clichéd",
  "From now on",
  "Leadership competence",
  "Create payroll accounting",
  "Salary expectations",
  "Get to",
  "Basic requirement",
  "In heaps",
  "Filter out",
  "Get along with",
  "Fellow students",
  "Communication skills",
  "Conflict ability",
  "Customer orientation",
  "Educational",
  "Warn employees",
  "To make curious",
  "Frank packages",
  "To show precisely",
  "Plausible",
  "Negotiate prices",
  "Grant discounts",
  "Write invoices",
  "Handle complaints",
  "Fail at",
  "Keep up to date",
  "Get an overview of",
  "To delay",
  "List keywords",
  "Teamwork",
  "Deal with",
  "Negotiate with",
  "Avoid",
  "Waste",
  "Transfer",
  "Contract",
  "Confuse",
  "Do many things at once",
  "Assume",
  "Accept goods",
  "Assemble goods",
  "Check stock levels",
  "Waste time",
  "Determined",
  "Be responsible for",
];

var ger1 = [
  "Abgelenkt sein",
  "Angegestrebten berufslaufbahn",
  "Anwendung des Verballists",
  "Auf Biegen und Brechen versuchen",
  "Auf ehrlichkeit beruhren",
  "Aufschlussreich",
  "Ausführliche Darlegung seiner Motivation",
  "Auszeit",
  "Auswahl eines sympathischen Fotos",
  "Beurteilung",
  "Bewusst absolvierte",
  "Der arbeitsablauf",
  "Der erlesenem Genuss",
  "Der Gleichzeitigkeitswahn",
  "Der Richtungswechsel",
  "Der stellenwert",
  "Der studiengang",
  "Die Aufsteigchance",
  "Die auszeit",
  "Die Doppelbelastung",
  "Die fine kürfstliche lebensart",
  "Die Laufbahn",
  "Die Mobilität",
  "Die Promotion",
  "Die probanden",
  "Die stoßstange",
  "Die Zulassungs voraussetzung",
  "Ein abgebrochener Studiengang",
  "Ein bunter Lebenslauf",
  "Ein nur massig",
  "Einheillig wiedersprechen",
  "Ebenso zentral wie selbstverstandlich",
  "Enthält",
  "Erfreuen sich",
  "Fehler ausbügeln",
  "Freude schenken",
  "Fromt sich",
  "Genaue Beschreibung des berüflichen Werdegangs",
  "Grossen Beliebtheit",
  "Handlungsanweisungen",
  "Herstellung",
  "Im Hinblick",
  "Im zweifel gilt daher",
  "Innovationsschub",
  "Klarkommen",
  "Plausibel",
  "Reviedieren",
  "Ruchtungswechsel",
  "Schlüssig",
  "Stark steigender Nachfrage",
  "Stolpersteine",
  "Umgehen",
  "Vielfach prämierten Speisen",
  "Vollzogen",
  "Wahrnehmung",
  "Zeit verplempern",
  "Zielstrebig",
];

var eng1 = [
  "To be distracted",
  "Desired career path",
  "Application of the verbal list",
  "Try by hook or by crook",
  "Based on honesty",
  "Insightful, informative",
  "Detailed explanation of his motivation",
  "Timeout",
  "Selecting a sympathetic photo",
  "Assessment",
  "Consciously completed",
  "The work process",
  "The exquisite pleasure",
  "Simultaneity delusion",
  "Change of direction",
  "The importance",
  "The course of study",
  "The chance of promotion",
  "The timeout",
  "The double burden",
  "The fine princely way of life",
  "The career",
  "The mobility",
  "The promotion",
  "The test subjects",
  "The bumper",
  "The admission requirement",
  "A discontinued course of study",
  "A colorful resume",
  "Only moderately",
  "Unanimously contradict",
  "Just as central as self-evident",
  "Contains",
  "Enjoy",
  "Iron out errors",
  "Give joy",
  "Forms itself",
  "Detailed description of the professional career",
  "Great popularity",
  "Instructions",
  "Manufacturing",
  "In view",
  "Therefore, when in doubt",
  "Innovation boost",
  "Get along",
  "Plausible",
  "Reverse",
  "Direction change",
  "Conclusion",
  "Strongly increasing demand",
  "Stumbling blocks",
  "Avoid",
  "Multiple award-winning dishes",
  "Executed",
  "Perception",
  "Waste time",
  "Determined",
];
var ger2 = [
  "Abgelegenen",
  "Akribisch",
  "Analytisches und logisches Denken",
  "Arbeitsverhältnis",
  "Arbeitsverträge aufsetzen",
  "Auflichten",
  "Ausführlich",
  "Ballungsraum",
  "Beihalten",
  "Belastbarkeit",
  "Berühren",
  "Bescheid",
  "Bestellung versenden",
  "Betriebsräte",
  "Beweis",
  "Darbitten",
  "Der Reihe nach",
  "Der Wandel",
  "Die Kapazität",
  "Die Konsument",
  "Die Priorität",
  "Die Ressource",
  "Die Schlüsselqualifikation",
  "Durchsetzungsvermögen",
  "Einfühlungsvermögen",
  "Einer Illusion erliegen",
  "Etwas nicht gewachsen sein",
  "Fehler ausüben",
  "Floskelhaft",
  "Fortan",
  "Führungskompetenz",
  "Gehaltsabrechnungen erstellen",
  "Gehaltsvorstellungen",
  "Gelangen zu",
  "Grundvoraussetzung",
  "Haufenweise",
  "Herausfiltern",
  "Klarkommen mit",
  "Kommilitonen",
  "Kommunikationsfähigkeit",
  "Konfliktfähigkeit",
  "Kundenorientierung",
  "Lehrreich",
  "Mitarbeiter abmahnen",
  "Neugierig zu stimmen",
  "Pakete frankieren",
  "Passgenau aufzuzeigen",
  "Plausibel",
  "Preise aushandeln",
  "Rabatte gewähren",
  "Rechnungen schreiben",
  "Reklamationen bearbeiten",
  "Scheitern an",
  "Sich auf dem Laufenden halten",
  "Sich einen Überblick verschaffen über",
  "Sich verzögern",
  "Stichwortartig aufzählen",
  "Teamfähigkeit",
  "Umgehen mit",
  "Verhandlungen führen mit",
  "Vermeiden",
  "Verschwenden",
  "Versetzen",
  "Vertrag",
  "Verwechseln",
  "Vieles auf einmal tun",
  "Voraussetzen",
  "Waren annehmen",
  "Waren zusammenstellen",
  "Warenbestände prüfen",
  "Zeit verplempern",
  "Zielstrebig",
  "Zuständig sein für",
];

var eng2 = [
  "Remote",
  "Meticulous",
  "Analytical and logical thinking",
  "Employment relationship",
  "Set up employment contracts",
  "Light up",
  "Detailed",
  "Conurbation",
  "Hold on",
  "Resilience",
  "Touch",
  "Notice",
  "Send order",
  "Works councils",
  "Proof",
  "Offer",
  "In order",
  "The change",
  "The capacity",
  "The consumer",
  "The priority",
  "The resource",
  "The key qualification",
  "Assertiveness",
  "Empathy",
  "To succumb to an illusion",
  "Not being up to something",
  "Make a mistake",
  "Clichéd",
  "From now on",
  "Leadership competence",
  "Create payroll accounting",
  "Salary expectations",
  "Get to",
  "Basic requirement",
  "In heaps",
  "Filter out",
  "Get along with",
  "Fellow students",
  "Communication skills",
  "Conflict ability",
  "Customer orientation",
  "Educational",
  "Warn employees",
  "To make curious",
  "Frank packages",
  "To show precisely",
  "Plausible",
  "Negotiate prices",
  "Grant discounts",
  "Write invoices",
  "Handle complaints",
  "Fail at",
  "Keep up to date",
  "Get an overview of",
  "To delay",
  "List keywords",
  "Teamwork",
  "Deal with",
  "Negotiate with",
  "Avoid",
  "Waste",
  "Transfer",
  "Contract",
  "Confuse",
  "Do many things at once",
  "Assume",
  "Accept goods",
  "Assemble goods",
  "Check stock levels",
  "Waste time",
  "Determined",
  "Be responsible for",
];

var ger = ger1.concat(ger2);
console.log(ger);

var eng = eng1.concat(eng2);
console.log(eng);

var currentIndex = 0;
var germanDiv = document.querySelector(".german");
var englishDiv = document.querySelector(".eng");
var prevButton = document.getElementById("prevButton");
var nextButton = document.getElementById("nextButton");
var button1 = document.getElementById("button1");
var button2 = document.getElementById("button2");
var button3 = document.getElementById("button3");

function displayWord() {
  germanDiv.textContent = ger[currentIndex];
  englishDiv.textContent = "";
  button1.textContent = currentIndex + 1;
  button2.textContent = currentIndex + 2;
  button3.textContent = currentIndex + 3;
}

function displayPrevWord() {
  if (currentIndex > 0) {
    currentIndex--;
  }
  displayWord();
}

function displayNextWord() {
  if (currentIndex < ger.length - 3) {
    currentIndex++;
  }
  displayWord();
}

function displayWord1() {
  currentIndex = parseInt(button1.textContent) - 1;
  displayWord();
}

function displayWord2() {
  currentIndex = parseInt(button2.textContent) - 1;
  displayWord();
}

function displayWord3() {
  currentIndex = parseInt(button3.textContent) - 1;
  displayWord();
}

germanDiv.onclick = function () {
  englishDiv.textContent = eng[currentIndex];
};

// Display the first word when the page loads
displayWord();

prevButton.onclick = function (event) {
  event.preventDefault();
  displayPrevWord();
};

nextButton.onclick = function (event) {
  event.preventDefault();
  displayNextWord();
};

button1.onclick = function (event) {
  event.preventDefault();
  displayWord1();
};

button2.onclick = function (event) {
  event.preventDefault();
  displayWord2();
};

button3.onclick = function (event) {
  event.preventDefault();
  displayWord3();
};
